baseURL = "https://blog.mengchen.online"
languageCode = "zh-CN"
title = "ğŸŒŸè¡Œè€… åšå®¢"
theme = "maupassant"
googleAnalytics = ""  # UA-XXXXXXXX-X

## ä¿æŒåˆ†ç±»çš„åŸå§‹åå­—ï¼ˆfalseä¼šåšè½¬å°å†™å¤„ç†ï¼‰
preserveTaxonomyNames = true
## æ˜¯å¦ç¦æ­¢URL Pathè½¬å°å†™
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

defaultMarkdownHandler = "Goldmark"

#disqusShortname = "yourdiscussshortname"  ## æ˜¯å¦å¼€å¯disqusè¯„è®ºï¼Œä¸è¦å’ŒutterancåŒæ—¶å¼€å¯

[author]
  name = "MC"

[params]
  author = "æ˜Ÿè¡Œè€…"
  subtitle = "Android åç«¯èœé¸Ÿ"
  keywords = "java,kotlin,android,åç«¯"
  description = "Android åç«¯èœé¸Ÿ"
  busuanzi = true #å¯ç”¨ä¸ç®—å­ç½‘é¡µç»Ÿè®¡
  googleAd = ""  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # å¯ç”¨æœ¬åœ°æœç´¢

  # è¿™é‡Œæˆ‘å­˜æ”¾åœ¨äº†ä¸»é¢˜çš„staticæ–‡ä»¶å¤¹é‡Œï¼Œæ ¹ç›®å½•çš„ä¼¼ä¹ä¹Ÿå¯ä»¥
  customCSS = ['douban.css', 'other.css']
  # if ['custom.css'], load '/static/css/custom.css' file
  customJS = ['douban.js']
  # if ['custom.js'], load '/static/js/custom.js' file

  # å…¨å±€å¼€å…³ï¼Œä½ ä¹Ÿå¯ä»¥åœ¨æ¯ä¸€ç¯‡å†…å®¹çš„ front matter ä¸­é’ˆå¯¹å•ç¯‡å†…å®¹å…³é—­æˆ–å¼€å¯æŸäº›åŠŸèƒ½
  toc = true  # æ˜¯å¦å¼€å¯ç›®å½•

[taxonomies]
  category = "categories"
  tag = "tags"

## å‹æƒ…é“¾æ¥ï¼Œå¯ä»¥å¤šä¸ª

[[params.links]]
  title = "é£é›ªæ— æƒ…çš„åšå®¢"
  name = "é£é›ªæ— æƒ…çš„åšå®¢"
  url = "https://www.flysnow.org/"

## ä¾§è¾¹æ å¹¿å‘Šä½
# [[params.ads]]
#   title = "ã€2019åŒ12ã€‘ALL IN CLoud ä½è‡³1æŠ˜"
#   url = "https://www.aliyun.com/minisite/goods?userCode=jdg9oj97&share_source=copy_link"
#   img = "https://img.alicdn.com/tfs/TB1_rYHo7P2gK0jSZPxXXacQpXa-690-388.jpg"


## é…ç½® utterancè¯„è®º,æ•™ç¨‹å‚è€ƒ https://utteranc.es/
[params.utteranc]
  enable = true
  repo = "your github repo" ##æ¢æˆè‡ªå·±å¾—
  issueTerm = "pathname"
  theme = "github-light"

## å¼€å¯ç‰ˆæƒå£°æ˜ï¼Œåè®®åå­—å’Œé“¾æ¥éƒ½å¯ä»¥æ¢
[params.cc]
    name = "çŸ¥è¯†å…±äº«ç½²å-éå•†ä¸šæ€§ä½¿ç”¨-ç¦æ­¢æ¼”ç» 4.0 å›½é™…è®¸å¯åè®®"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

## é…ç½®ä»£ç é«˜äº®
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

## é…ç½®ç½‘ç«™èœå•

[menu]
  [[menu.main]]
    identifier = "tools"
    name = "å·¥å…·"
    url = "/tools/"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "å½’æ¡£"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    url = "/about"
    name = "å…³äº"

[params.valine]
    enable = true
    appId = 'Wh8pwLoR0pjRL97Q8rlJp9jS-gzGzoHsz'
    appKey = '4QT1DCo0KbARIjnlkGHV51KG'
    notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
    verify = false # Verification code
    avatar = 'mm' 
    placeholder = 'è¯´ç‚¹ä»€ä¹ˆå§...'
    visitor = true